name : null 
channels :
   - nvidia
   - rapidsai
   - pytorch
   - conda-forge
dependencies :
  - python=3.10
  - pytorch-lightning
  - rapids=23.02
  - tensorflow
  - jax
  - git
  - jupyterlab
  - jupyterlab-nvdashboard
  - dask-labextension
  - umap-learn
  - wandb
  - lightgbm
  - gh
  - holoviews
  - hvplot
  - graphistry
  - pycaret
  - ray-tune
  - torchvision
  - torchaudio

