name: machine-learning-2022.11

channels:
  - nvidia
  - rapidsai
  - conda-forge
  - defaults

dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _tflow_select=2.3.0
  - abseil-cpp=20211102.0
  - absl-py=1.3.0
  - aiohttp=3.8.3
  - aiosignal=1.2.0
  - alembic=1.8.1
  - anyio=3.6.2
  - appdirs=1.4.4
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - arrow-cpp=9.0.0
  - astor=0.8.1
  - asttokens=2.1.0
  - astunparse=1.6.3
  - async-timeout=4.0.2
  - atk-1.0=2.36.0
  - attrs=22.1.0
  - aws-c-cal=0.5.11
  - aws-c-common=0.6.2
  - aws-c-event-stream=0.2.7
  - aws-c-io=0.10.5
  - aws-checksums=0.1.11
  - aws-sdk-cpp=1.8.186
  - babel=2.10.3
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - bcrypt=3.2.2
  - beautifulsoup4=4.11.1
  - blas=2.116
  - blas-devel=3.9.0
  - bleach=5.0.1
  - blinker=1.5
  - blosc=1.21.1
  - bokeh=2.4.3
  - boost=1.74.0
  - boost-cpp=1.74.0
  - bottleneck=1.3.5
  - branca=0.5.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.9.24
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=4.2.4
  - cairo=1.16.0
  - catalogue=2.0.8
  - catboost=1.1.1
  - certifi=2022.9.24
  - cffi=1.15.1
  - cfitsio=4.1.0
  - charset-normalizer=2.1.1
  - chart-studio=1.1.0
  - click=8.1.3
  - click-plugins=1.1.1
  - cligj=0.7.2
  - cloudpickle=2.2.0
  - cmake=3.24.3
  - colorama=0.4.6
  - colorcet=3.0.1
  - colorlover=0.3.0
  - confection=0.0.3
  - configparser=5.3.0
  - confuse=2.0.0
  - contourpy=1.0.6
  - cryptography=38.0.2
  - cubinlinker=0.2.0
  - cucim=22.10.00
  - cuda-python=11.7.0
  - cudatoolkit=11.7.0
  - cudf=22.10.00
  - cudf_kafka=22.10.00
  - cudnn=8.4.1.50
  - cufflinks-py=0.17.3
  - cuml=22.10.00
  - cupy=11.2.0
  - curl=7.86.0
  - cusignal=22.10.01
  - cuspatial=22.10.00
  - custreamz=22.10.00
  - cuxfilter=22.10.00
  - cycler=0.11.0
  - cymem=2.0.7
  - cyrus-sasl=2.1.27
  - cython-blis=0.7.8
  - cytoolz=0.12.0
  - dash=2.6.2
  - dask=2022.9.2
  - dask-core=2022.9.2
  - dask-cuda=22.10.00
  - dask-cudf=22.10.00
  - dask-labextension=6.0.0
  - dask-sql=2022.10.1
  - databricks-cli=0.17.3
  - dataclasses=0.8
  - datashader=0.13.1a
  - datashape=0.5.4
  - datefinder=0.7.3
  - debugpy=1.6.3
  - decorator=5.1.1
  - defusedxml=0.7.1
  - distributed=2022.9.2
  - dlpack=0.5
  - docker-py=6.0.0
  - docker-pycreds=0.4.0
  - entrypoints=0.4
  - etils=0.9.0
  - executing=1.2.0
  - expat=2.5.0
  - faiss-proc=1.0.0
  - fastapi=0.85.2
  - fastavro=1.7.0
  - fastrlock=0.8
  - fftw=3.3.10
  - fiona=1.8.21
  - flask=2.2.2
  - flask-compress=1.13
  - flit-core=3.7.1
  - folium=0.13.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.1
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.38.0
  - freetype=2.12.1
  - freexl=1.0.6
  - fribidi=1.0.10
  - frozenlist=1.3.1
  - fsspec=2022.10.0
  - funcy=1.17
  - future=0.18.2
  - gast=0.4.0
  - gdal=3.5.1
  - gdk-pixbuf=2.42.8
  - gensim=4.2.0
  - geopandas=0.12.1
  - geopandas-base=0.12.1
  - geos=3.11.0
  - geotiff=1.7.1
  - gettext=0.21.1
  - gflags=2.2.2
  - gh=2.18.1
  - giflib=5.2.1
  - git=2.38.1
  - gitdb=4.0.9
  - gitpython=3.1.29
  - glib=2.74.1
  - glib-tools=2.74.1
  - glog=0.6.0
  - gmp=6.2.1
  - google-auth=1.35.0
  - google-auth-oauthlib=0.4.6
  - google-pasta=0.2.0
  - graphistry=0.28.5
  - graphite2=1.3.13
  - graphviz=6.0.1
  - greenlet=1.1.3.post0
  - grpc-cpp=1.46.4
  - grpcio=1.46.4
  - gtk2=2.24.33
  - gts=0.7.6
  - gunicorn=20.1.0
  - h11=0.14.0
  - h5py=3.7.0
  - harfbuzz=5.3.0
  - hdf4=4.2.15
  - hdf5=1.12.2
  - heapdict=1.0.1
  - holoviews=1.14.6
  - htmlmin=0.1.12
  - hvplot=0.8.1
  - icu=70.1
  - idna=3.4
  - imagecodecs-lite=2019.12.3
  - imagehash=4.3.1
  - imageio=2.22.0
  - imbalanced-learn=0.9.1
  - importlib-metadata=5.0.0
  - importlib_resources=5.10.0
  - ipycytoscape=1.3.3
  - ipykernel=6.17.0
  - ipython=8.6.0
  - ipython_genutils=0.2.0
  - ipywidgets=8.0.2
  - itsdangerous=2.1.2
  - jax=0.3.23
  - jaxlib=0.3.15
  - jbig=2.1
  - jedi=0.18.1
  - jinja2=3.1.2
  - joblib=1.2.0
  - jpeg=9e
  - json-c=0.16
  - json5=0.9.5
  - jsonschema=4.17.0
  - jupyter-server-mathjax=0.2.6
  - jupyter-server-proxy=3.2.2
  - jupyter_client=7.3.4
  - jupyter_core=4.11.1
  - jupyter_server=1.21.0
  - jupyterlab=3.5.0
  - jupyterlab-git=0.39.3
  - jupyterlab-nvdashboard=0.7.0
  - jupyterlab_pygments=0.2.2
  - jupyterlab_server=2.16.2
  - jupyterlab_widgets=3.0.3
  - kealib=1.4.15
  - keras=2.9.0
  - keras-preprocessing=1.1.2
  - keyutils=1.6.1
  - kiwisolver=1.4.4
  - kmodes=0.12.2
  - krb5=1.19.3
  - langcodes=3.3.0
  - lcms2=2.12
  - ld_impl_linux-64=2.39
  - lerc=4.0.0
  - libabseil=20211102.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcucim=22.10.00
  - libcudf=22.10.00
  - libcudf_kafka=22.10.00
  - libcugraph=22.10.00
  - libcugraph_etl=22.10.00
  - libcugraphops=22.10.00
  - libcuml=22.10.00
  - libcumlprims=22.10.00
  - libcurl=7.86.0
  - libcusolver=11.4.1.48
  - libcusparse=11.7.5.86
  - libcuspatial=22.10.00
  - libdap4=3.20.6
  - libdeflate=1.14
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libfaiss=1.7.0
  - libffi=3.4.2
  - libgcc-ng=12.2.0
  - libgcrypt=1.10.1
  - libgd=2.3.3
  - libgdal=3.5.1
  - libgfortran-ng=12.2.0
  - libgfortran5=12.2.0
  - libglib=2.74.1
  - libgoogle-cloud=1.40.2
  - libgpg-error=1.45
  - libgsasl=1.10.0
  - libiconv=1.17
  - libkml=1.3.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm11=11.1.0
  - libnetcdf=4.8.1
  - libnghttp2=1.47.0
  - libnsl=2.0.0
  - libntlm=1.4
  - libopenblas=0.3.21
  - libpng=1.6.38
  - libpq=14.5
  - libprotobuf=3.20.1
  - libraft-distance=22.10.00
  - libraft-headers=22.10.00
  - libraft-nn=22.10.00
  - librdkafka=1.7.0
  - librmm=22.10.00
  - librsvg=2.54.4
  - librttopo=1.1.0
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libspatialite=5.0.1
  - libsqlite=3.39.4
  - libssh2=1.10.0
  - libstdcxx-ng=12.2.0
  - libthrift=0.16.0
  - libtiff=4.4.0
  - libtool=2.4.6
  - libutf8proc=2.8.0
  - libuuid=2.32.1
  - libuv=1.44.2
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libxgboost=1.6.2dev.rapidsai22.10
  - libxml2=2.10.3
  - libzip=1.9.2
  - libzlib=1.2.13
  - lightgbm=3.3.3
  - llvm-openmp=14.0.4
  - llvmlite=0.39.1
  - locket=1.0.0
  - lz4=4.0.2
  - lz4-c=1.9.3
  - magma=2.5.4
  - mako=1.2.3
  - mapclassify=2.4.3
  - markdown=3.4.1
  - markupsafe=2.1.1
  - matplotlib-base=3.6.1
  - matplotlib-inline=0.1.6
  - missingno=0.4.2
  - mistune=2.0.4
  - mkl=2022.1.0
  - mkl-include=2022.1.0
  - mlflow=1.30.0
  - mlxtend=0.21.0
  - mpfr=4.1.0
  - msgpack-python=1.0.4
  - multidict=6.0.2
  - multimethod=1.4
  - multipledispatch=0.6.0
  - munch=2.5.0
  - munkres=1.1.4
  - murmurhash=1.0.9
  - nbclassic=0.4.5
  - nbclient=0.7.0
  - nbconvert=7.2.3
  - nbconvert-core=7.2.3
  - nbconvert-pandoc=7.2.3
  - nbdime=3.1.1
  - nbformat=5.7.0
  - nccl=2.14.3.1
  - ncurses=6.3
  - nest-asyncio=1.5.6
  - networkx=2.6.3
  - ninja=1.11.0
  - nltk=3.6.7
  - nodejs=18.11.0
  - noise=1.2.2
  - nomkl=3.0
  - notebook=6.5.1
  - notebook-shim=0.2.0
  - nspr=4.32
  - nss=3.78
  - numba=0.56.3
  - numexpr=2.8.3
  - numpy=1.23.4
  - nvtx=0.2.3
  - oauthlib=3.2.2
  - olefile=0.46
  - openblas=0.3.21
  - openjpeg=2.4.0
  - openssl=1.1.1s
  - opt_einsum=3.3.0
  - orc=1.7.6
  - packaging=21.3
  - palettable=3.3.0
  - pandas=1.5.1
  - pandas-profiling=3.0.0
  - pandoc=2.19.2
  - pandocfilters=1.5.0
  - panel=0.12.7
  - pango=1.50.11
  - param=1.12.2
  - paramiko=2.11.0
  - parquet-cpp=1.5.1
  - parso=0.8.3
  - partd=1.3.0
  - pathtools=0.1.2
  - pathy=0.6.2
  - patsy=0.5.3
  - pcre=8.45
  - pcre2=10.37
  - perl=5.32.1
  - pexpect=4.8.0
  - phik=0.12.2
  - pickleshare=0.7.5
  - pillow=9.2.0
  - pip=22.3
  - pixman=0.40.0
  - pkgutil-resolve-name=1.3.10
  - plotly=5.11.0
  - poppler=22.04.0
  - poppler-data=0.4.11
  - postgresql=14.5
  - preshed=3.0.8
  - proj=9.0.1
  - prometheus_client=0.15.0
  - prometheus_flask_exporter=0.20.3
  - promise=2.3
  - prompt-toolkit=3.0.31
  - protobuf=3.20.1
  - psutil=5.9.3
  - pthread-stubs=0.4
  - ptxcompiler=0.7.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - py-xgboost=1.6.2dev.rapidsai22.10
  - pyarrow=9.0.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pybind11-abi=4
  - pycaret=2.2.3
  - pycparser=2.21
  - pyct=0.4.6
  - pyct-core=0.4.6
  - pydantic=1.10.2
  - pydeck=0.5.0
  - pydeprecate=0.3.2
  - pyee=8.1.0
  - pygments=2.13.0
  - pyjwt=2.6.0
  - pyldavis=3.3.1
  - pylibcugraph=22.10.00
  - pylibraft=22.10.00
  - pynacl=1.5.0
  - pynndescent=0.5.8
  - pynvml=11.4.1
  - pyod=1.0.6
  - pyopenssl=22.1.0
  - pyparsing=3.0.9
  - pyppeteer=1.0.2
  - pyproj=3.4.0
  - pyrsistent=0.19.1
  - pysocks=1.7.1
  - python=3.9.13
  - python-confluent-kafka=1.7.0
  - python-cufflinks=0.17.3
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python-flatbuffers=1.12
  - python-graphviz=0.20.1
  - python-tzdata=2022.5
  - python_abi=3.9
  - pytorch=1.12.1
  - pytorch-lightning=1.6.5
  - pytz=2022.5
  - pytz-deprecation-shim=0.1.0.post0
  - pyu2f=0.1.5
  - pyviz_comms=2.2.1
  - pywavelets=1.3.0
  - pywin32-on-windows=0.1.0
  - pyyaml=6.0
  - pyzmq=24.0.1
  - querystring_parser=1.2.4
  - raft-dask=22.10.00
  - rapids=22.10.00
  - rapids-xgboost=22.10.00
  - re2=2022.06.01
  - readline=8.1.2
  - regex=2022.10.31
  - requests=2.28.1
  - requests-oauthlib=1.3.1
  - retrying=1.3.3
  - rhash=1.4.3
  - rmm=22.10.00
  - rsa=4.9
  - rtree=1.0.1
  - s2n=1.0.10
  - scikit-image=0.19.3
  - scikit-learn=1.1.3
  - scipy=1.9.3
  - seaborn=0.12.0
  - seaborn-base=0.12.0
  - send2trash=1.8.0
  - sentry-sdk=1.10.1
  - setproctitle=1.3.2
  - setuptools=59.5.0
  - shapely=1.8.5
  - shellingham=1.5.0
  - shortuuid=1.0.9
  - simpervisor=0.4
  - six=1.16.0
  - sleef=3.5.1
  - smart_open=5.2.1
  - smmap=3.0.5
  - snappy=1.1.9
  - sniffio=1.3.0
  - sortedcontainers=2.4.0
  - soupsieve=2.3.2.post1
  - spacy=3.4.2
  - spacy-legacy=3.0.10
  - spacy-loggers=1.0.3
  - spdlog=1.8.5
  - spectate=1.0.1
  - sqlalchemy=1.4.42
  - sqlite=3.39.4
  - sqlparse=0.4.3
  - squarify=0.4.3
  - srsly=2.4.5
  - stack_data=0.6.0
  - starlette=0.20.4
  - statsmodels=0.13.4
  - streamz=0.6.4
  - tabulate=0.9.0
  - tangled-up-in-unicode=0.2.0
  - tbb=2021.6.0
  - tblib=1.7.0
  - tenacity=8.1.0
  - tensorboard=2.9.0
  - tensorboard-data-server=0.6.0
  - tensorboard-plugin-wit=1.8.1
  - tensorflow=2.9.1
  - tensorflow-base=2.9.1
  - tensorflow-estimator=2.9.1
  - termcolor=2.1.0
  - terminado=0.17.0
  - textblob=0.15.3
  - thinc=8.1.5
  - threadpoolctl=3.1.0
  - tifffile=2020.6.3
  - tiledb=2.11.3
  - tinycss2=1.2.1
  - tk=8.6.12
  - tomli=2.0.1
  - toolz=0.12.0
  - torchmetrics=0.10.1
  - torchvision=0.13.0
  - tornado=6.1
  - tqdm=4.64.1
  - traitlets=5.5.0
  - treelite=3.0.0
  - typer=0.4.2
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - tzcode=2022e
  - tzdata=2022f
  - tzlocal=4.2
  - ucx=1.13.1
  - ucx-proc=1.0.0
  - ucx-py=0.28.00
  - umap-learn=0.5.3
  - unicodedata2=15.0.0
  - urllib3=1.26.11
  - uvicorn=0.19.0
  - visions=0.7.1
  - wandb=0.13.4
  - wasabi=0.10.0
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=1.4.1
  - websockets=10.4
  - werkzeug=2.2.2
  - wheel=0.37.1
  - widgetsnbextension=4.0.3
  - wordcloud=1.8.2.2
  - wrapt=1.14.1
  - xarray=2022.10.0
  - xarray-spatial=0.3.5
  - xerces-c=3.2.4
  - xeus=2.4.1
  - xeus-python=0.14.3
  - xeus-python-shell=0.5.0
  - xeus-python-shell-raw=0.5.0
  - xgboost=1.6.2dev.rapidsai22.10
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.7.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xyzservices=2022.9.0
  - xz=5.2.6
  - yaml=0.2.5
  - yarl=1.8.1
  - yellowbrick=1.5
  - zeromq=4.3.4
  - zict=2.2.0
  - zipp=3.10.0
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
    - cugraph==22.10.0+2.gfad6af4e.dirty
    - treelite-runtime==3.0.0