name: machine-learning-2021.09

channels:
  - rapidsai
  - nvidia
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - rapids=22.08
  - dask-sql=2022.8.0
  - jupyterlab=3.4.5
  - dash=2.6.1
  - graphistry=0.27.1
  - pycaret=2.2.3
  - xarray-spatial=0.3.5
  - astunparse=1.6.3
  - bokeh
  - captum
  - cudnn

  - cupy
  - dask
  - dask-ml
  - dask-labextension
  - datashader
  - featuretools
  - gast=0.3.3
  - gh
  - git
  - google-pasta=0.2.0
  - grpcio=1.32
  - h5py=2.10
  - holoviews
  - hvplot
  - imbalanced-learn
  - jupyterlab
  - jupyterlab-git
  - jupyterlab-lsp
  - jupyterlab-nvdashboard
  - keras-preprocessing=1.1
  - lightgbm
  - matplotlib
  - nccl
  - numba
  - numpy=1.19.5
  - optuna
  - pandas
  - panel
  - pip
  - pip:
    - -r requirements.txt
  - pyarrow
  - python=3.8
  - python-flatbuffers=1.12
  - python-language-server
  - pytorch=1.7
  - pytorch-lightning
  - pyviz_comms
  - rapids-blazing=21.06
  - scikit-learn
  - scipy
  - shap
  - six=1.15
  - tensorboard=2.4
  - termcolor=1.1
  - torchaudio
  - torchtext
  - torchvision
  - typing-extensions=3.7
  - umap-learn
  - wandb
  - xarray
  - xeus-python
  - xgboost
