name: null
channels:
  - pytorch
  - nvidia
  - rapidsai-nightly
  - conda-forge
  - defaults
dependencies:
  - rapids=24.08
  - python=3.11
  - cuda-version[version='>=12.0,<=12.5']
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda
  - jupyterlab
  - dash
  - graphistry
  - tensorflow
  - xarray-spatial
  - dask-sql
  - code-server
  - dask-ml
  - torchinfo
  - seaborn
  - jax
  - dask-labextension
  - streamlit
  - streamlit-folium
  - wandb
  - gh
  - lightgbm
  - git
  - umap-learn
  - prophet
  - ignite
  - texlab
  - webcolors
  - r-languageserver
  - python-language-server
  - jedi-language-server
  - jsonschema-with-format-nongpl