name: null 
channels:
  - nvidia
  - rapidsai
  - pytorch
  - conda-forge
dependencies:
  - python=3.9
  - pytorch-lightning
  - rapids=23.10
  - tensorflow
  - jax
  - git
  - jupyterlab
  - jupyterlab-nvdashboard
  - dask-labextension
  - umap-learn
  - wandb
  - lightgbm
  - gh
  - holoviews
  - hvplot
  - graphistry
  - pycaret
  - xarray-spatial
  - ray-tune
  - torchvision
  - torchaudio
  - netcdf4
  - streamlit
  - folium
  - streamlit-folium
  - prophet
  - ignite
  - jsonschema-with-format-nongpl
  - jedi-language-server
  - pyright
  - python-language-server
  - r-languageserver
  - texlab
  - ca-certificates
  - certifi
  - openssl
  - webcolors
  - seaborn
  - dask-kubernetes
  - skorch
  - tune-sklearn
  - ipykernel
  - dask-ml
  - kubernetes
  - google-cloud-sdk
  - gcsfs
  - optuna
  - pip
  - pip :
    - torch-summary
    - jupyter_ai

