# add channels for rapids, tensorflow for gpu, pytorch-lightning, and torchvision
name: machine-learning-2022.09
channels:
  - rapidsai
  - rapidsai-nightly
  - nvidia
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - cudatoolkit=11.2
  - rapids=22.08
  - dask-sql=2022.8.0
  - jupyterlab=3.4.5
  - dash=2.6.1
  - graphistry=0.27.1
  - pycaret=2.2.3
  - xarray-spatial=0.3.5
  - jupyterlab-nvdashboard
  - torchaudio=0.12.1
  - torchtext=0.13.1
  - torchvision=0.13.1
  - pytorch=1.12.1
  - pytorch-lightning=1.6.5
  # - grpc-cpp>=1.42.0,<1.47.0a0
  # - icu>=69.1,<70.0a0
  - jax=0.3.17
  - jaxlib=0.3.15
  - pip=22.1.2
  - pip:
    - -r file:requirements.txt

  # - hdf5 >=1.10.6,<1.10.7.0a0
  # - tensorflow-base=2.*
  # - tensorflow=2.*